// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5VkDX-823ipZDeCZ-YVScNOXmaeRadtI',
    appId: '1:849817401604:web:2bc203077706eea8c1b851',
    messagingSenderId: '849817401604',
    projectId: 'expense-app-a7692',
    authDomain: 'expense-app-a7692.firebaseapp.com',
    databaseURL: 'https://expense-app-a7692-default-rtdb.firebaseio.com',
    storageBucket: 'expense-app-a7692.appspot.com',
    measurementId: 'G-XYXC593YB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBApWw6ZP71YJIqvtSQYG7rnQ5EU6HBtpQ',
    appId: '1:849817401604:android:ddcadcebdb3bdedcc1b851',
    messagingSenderId: '849817401604',
    projectId: 'expense-app-a7692',
    databaseURL: 'https://expense-app-a7692-default-rtdb.firebaseio.com',
    storageBucket: 'expense-app-a7692.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_FdMKt8J7ts5GdizgM9DQ_sAsaXC345w',
    appId: '1:849817401604:ios:cbf144cd43334e90c1b851',
    messagingSenderId: '849817401604',
    projectId: 'expense-app-a7692',
    databaseURL: 'https://expense-app-a7692-default-rtdb.firebaseio.com',
    storageBucket: 'expense-app-a7692.appspot.com',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_FdMKt8J7ts5GdizgM9DQ_sAsaXC345w',
    appId: '1:849817401604:ios:cbf144cd43334e90c1b851',
    messagingSenderId: '849817401604',
    projectId: 'expense-app-a7692',
    databaseURL: 'https://expense-app-a7692-default-rtdb.firebaseio.com',
    storageBucket: 'expense-app-a7692.appspot.com',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5VkDX-823ipZDeCZ-YVScNOXmaeRadtI',
    appId: '1:849817401604:web:18b51a8415a3f805c1b851',
    messagingSenderId: '849817401604',
    projectId: 'expense-app-a7692',
    authDomain: 'expense-app-a7692.firebaseapp.com',
    databaseURL: 'https://expense-app-a7692-default-rtdb.firebaseio.com',
    storageBucket: 'expense-app-a7692.appspot.com',
    measurementId: 'G-2ZTWB86MPM',
  );
}
